server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          globalcors:
            cors-configurations:
              "[/**]":
                allowedOrigins: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                  - PATCH
                allowedHeaders: "*"
                allowCredentials: false
                maxAge: 3600
  data:
    redis:
      host: localhost
      port: 6379
      password: redis123
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

jwt:
  secret: mySecretKeyForJWTTokenGenerationAndValidationThisIsAVeryLongSecretKeyForHS512Algorithm

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
    instances:
      authServiceCircuitBreaker:
        baseConfig: default
      customerServiceCircuitBreaker:
        baseConfig: default
      passiveProductServiceCircuitBreaker:
        baseConfig: default
      activeProductServiceCircuitBreaker:
        baseConfig: default
      transactionServiceCircuitBreaker:
        baseConfig: default
      debitCardServiceCircuitBreaker:
        baseConfig: default
      transferServiceCircuitBreaker:
        baseConfig: default
      reportServiceCircuitBreaker:
        baseConfig: default
      yankiServiceCircuitBreaker:
        baseConfig: default
      bootcoinServiceCircuitBreaker:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 2s
        cancelRunningFuture: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      access: read-only

logging:
  level:
    root: INFO
    com.finnova: DEBUG
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
