server:
  port: 8086

spring:
  application:
    name: digital-wallet-service

  data:
    mongodb:
      uri: mongodb://devandre:passw0rd1@localhost:27017/bootcoin_db?authSource=admin
      auto-index-creation: false

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

services:
  gateway:
    url: ${GATEWAY_URL:http://localhost:8080}
  products-service:
    url: ${PRODUCTS_SERVICE_URL:http://products-service}
  card-service:
    url: ${CARD_SERVICE_URL:http://card-service}

# Resilience4j Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
      transactionService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50

  timelimiter:
    instances:
      productService:
        timeoutDuration: 2s
      transactionService:
        timeoutDuration: 2s

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.finnova.digital_wallet_service: DEBUG
    org.springframework.web: INFO
    org.springframework.kafka: INFO

# OpenAPI/Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
