server:
  port: 8086

spring:
  application:
    name: digital-wallet-service

  data:
    mongodb:
      uri: mongodb://devandre:passw0rd1@localhost:27017/digital_wallet_db?authSource=admin
      auto-index-creation: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      cardService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
  timelimiter:
    instances:
      cardService:
        timeoutDuration: 2s

logging:
  level:
    com.finnova.digital_wallet_service: DEBUG
